apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-dev
  namespace: esprit-market
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/esprit_market?connectTimeout=10&socketTimeout=30"
  SPRING_DATASOURCE_USERNAME: "postgres"
  APP_CORS_ALLOWED_ORIGINS: "https://dev.esprit.thesphynx.net,http://localhost:4200"
  SERVER_PORT: "8088"
  JWT_EXPIRATION: "3600000"
  JWT_REFRESH_EXPIRATION: "604800000"
  COURIER_SCHEDULER_PENDING_TO_REFUSED_CRON: "0 0 0 * * *"
  COURIER_SCHEDULER_PENDING_TO_REFUSED_THRESHOLD: "P5D"
  FLASK_URL: "http://ml-service:8000"
