apiVersion: v1
kind: Secret
metadata:
  name: backend-secret-dev
  namespace: esprit-market
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "5E*Q1<,ku_{8"
  JWT_SECRET: "dQy5bL7rCtFTeN/LcSsgGVFtP43RBLsMNZMJ3qrUMEs="
