apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: esprit-market-backend-pdb
  namespace: esprit-market
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: esprit-market-backend
