apiVersion: v1
kind: Service
metadata:
  name: esprit-market-frontend
  namespace: esprit-market
  labels:
    app: esprit-market-frontend
spec:
  selector:
    app: esprit-market-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
