apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: esprit-market

resources:
  - ../../

images:
  - name: thesphynx2000/espritmarket-backend
    newTag: latest
  - name: thesphynx2000/espritmarket-frontend
    newTag: latest

commonLabels:
  - name: esprit-market-backend
  - name: esprit-market-frontend

patches:
  - path: patches/backend-patch.yaml
    target:
      kind: Deployment
      name: esprit-market-backend
  - path: patches/frontend-patch.yaml
    target:
      kind: Deployment
      name: esprit-market-frontend
